### ISSUE TITLE
ERROR: No such file or directory

### ISSUE THREAD

**Issue by zby1234** [wlerin/showroom#18]
~/showroom# python3 showroom.py --all
Show (S)chedule, Show (D)ownloads, Show (L)inks, (Q)uit
Current Time is 22:23
Watching Imamura Mitsuki's Showroom
Watching Fukuda Akari's Showroom
Watching Takino Yumiko's Showroom
Watching Fujiwara Azusa's Showroom
Watching Mori Kaho's Showroom
Watching Nakamura Izumi's Showroom
Watching Kawakami Rena's Showroom
Watching Matsumoto Chikako's Showroom
Watching Ota Nao's Showroom
Watching Shimizu Maria's Showroom
Downloading Imamura Mitsuki's Showroom
Downloading Fukuda Akari's Showroom
Downloading Takino Yumiko's Showroom
Downloading Fujiwara Azusa's Showroom
Downloading Mori Kaho's Showroom
Downloading Nakamura Izumi's Showroom
Downloading Kawakami Rena's Showroom
Downloading Matsumoto Chikako's Showroom
: No such file or directory
Downloading Shimizu Maria's Showroom
: No such file or directory
: No such file or directory
: No such file or directory
: No such file or directory
: No such file or directory
: No such file or directory
: No such file or directory
: No such file or directory
: No such file or directory

**Comment by wlerin** [comment]
Update to the master branch, new-index is no longer supported. (It should never have been the default in the first place but I didn't understand how to use git early on.)
