### ISSUE TITLE
Use unique names for Official Room(s)

### ISSUE THREAD

**Issue by skeith** [wlerin/showroom#20]
These are duplicate names

https://github.com/wlerin/showroom/blob/7872293b973524f521886632bdd6d747ccaab503/index/other.jdex#L261
https://github.com/wlerin/showroom/blob/7872293b973524f521886632bdd6d747ccaab503/index/idol.jdex#L21
https://github.com/wlerin/showroom/blob/7872293b973524f521886632bdd6d747ccaab503/index/nogi46.jdex#L21

**Comment by wlerin** [comment]
Hmm. They are named that way because the other part of the name is in the group field. But it makes it hard (read: impossible) to select them for recording like this.

**Comment by wlerin** [comment]
Here's a question: Would people prefer these and the other "official rooms" to be in the SP folder, or in their respective group folders? (edit: went with option 2)

**Comment by wlerin** [comment]
Should be fixed with 0d2cfe0da66372c846eea3cbf3863e9f52cad7fd
