### ISSUE TITLE
"websocket" required for newer version of python user

### ISSUE THREAD

**Issue by amane1234** [wlerin/showroom#26]
I believe due to the version update of python3 (Not really sure), user should install manually "websocket-client" which is not described in your read.md

I tried several times with "websocket" (not websocket-client) it gives error :

[NameError: name 'ABNF' is not defined]

However, "websocket-client" works perfectly for my system

Therefore, I suggest to add "websocket-client" on requirement.txt or add description on read.md

Thanks!

**Comment by wlerin** [comment]
Ah I forgot about that. Yeah, that needs to be updated.

**Comment by wlerin** [comment]
Fixed by 96b9b01
