### ISSUE TITLE
About live recording

### ISSUE THREAD

**Issue by fusaku** [wlerin/showroom#31]
When recording the live broadcast, sometimes the live broadcast suddenly stops. After the live broadcast is resumed, only the video part before the live broadcast stop can be recorded, and the resumed video part cannot continue to be recorded. However, the audio will continue to be recorded. Is there any solution?

**Comment by wlerin** [comment]
Sorry it took me so long to notice this. I don't quite understand the issue? I assume you're on the master (i.e. ffmpeg-dependent) branch? Showroom's HLS streaming is standards non-compliant in various ways so using FFmpeg is a crapshoot at times. This is why the hls-python branch exists, but that also has problems--chief among them being it doesn't create a single video file, but saves each segment individually.

**Comment by fusaku** [comment]
Thank you very much for your reply. I see, I've been using master. I'll try switching to hls-python.
